#include "LfDataToolsScreen.h"
#include <ctype.h>
#include <esp_system.h>
#include "core/Device.h"
#include "core/ScreenManager.h"
#include "ui/actions/InputTextAction.h"
#include "ui/actions/ShowStatusAction.h"
#include "utils/IdentityFile.h"

namespace {
String bn(const String&p){int s=p.lastIndexOf('/');return s>=0?p.substring(s+1):p;}
String stem(String p){p=bn(p);int d=p.lastIndexOf('.');if(d>0)p.remove(d);return p;}
String clean(String n){n.trim();if(n.endsWith(".bin"))n.remove(n.length()-4);for(int i=0;i<(int)n.length();++i){char c=n[i];if(!(isalnum((unsigned char)c)||c=='-'||c=='_'))n.setCharAt(i,'_');}while(n.indexOf("__")>=0)n.replace("__","_");while(n.startsWith("_"))n.remove(0,1);while(n.endsWith("_"))n.remove(n.length()-1);return n;}
String uniquePath(const String&dir,const String&base){String p=dir+"/"+base+".bin";if(!Uni.Storage->exists(p.c_str()))return p;for(int n=2;n<1000;++n){p=dir+"/"+base+"_("+String(n)+").bin";if(!Uni.Storage->exists(p.c_str()))return p;}return "";}
}

const char* LfDataLibraryScreen::title(){return _state==BROWSE?"Saved LF Data":(_state==DETAILS?"LF Data Details":"LF Data Actions");}
void LfDataLibraryScreen::onInit(){_browser.root=_dir;open();}
void LfDataLibraryScreen::open(){_state=BROWSE;if(!Uni.Storage||!Uni.Storage->isAvailable()){ShowStatusAction::show("Storage unavailable",1600);Screen.goBack();return;}Uni.Storage->makeDir("/unigeek");Uni.Storage->makeDir(_dir.c_str());_browser.root=_dir;setItems(_browser.items(),_browser.load(this,_browseDir,".bin",nullptr,BrowseFileView::NAME,nullptr,_browseDir==_dir?"dictionaries":nullptr));}
bool LfDataLibraryScreen::load(const String&p){auto info=LFCodec::fromFilename(p);if(!info||!Uni.Storage||!Uni.Storage->isAvailable())return false;fs::File f=Uni.Storage->open(p.c_str(),"r");if(!f||f.size()!=info->dataSize){if(f)f.close();return false;}uint8_t raw[LFCodec::kMaxDataSize]={};size_t n=f.read(raw,info->dataSize);f.close();return n==info->dataSize&&LFCodec::decode(info->protocol,raw,n,_data);}
void LfDataLibraryScreen::details(){_state=DETAILS;_dc=0;auto add=[&](String l,String v){if(_dc>=9)return;_dl[_dc]=l;_dv[_dc]=v;_details[_dc]={_dl[_dc].c_str(),_dv[_dc]};++_dc;};add("File",bn(_path));auto info=LFCodec::format(_data.protocol);add("Type",info?info->name:"Unknown");LFCodec::Field f[6];size_t n=LFCodec::fields(_data,f,6);for(size_t i=0;i<n&&_dc<9;++i)add(f[i].label,f[i].value);add("Size",String(_data.length)+" bytes");_details[_dc++]={"[Press]","Actions"};_detailsView.resetScroll();_detailsView.setRows(_details,_dc);render();}
void LfDataLibraryScreen::onItemSelected(uint8_t i){if(_state==BROWSE){if(i>=_browser.count())return;auto e=_browser.entry(i);if(e.isDir){_browseDir=e.path;open();return;}if(!load(e.path)){ShowStatusAction::show("Data not supported",1600);return;}_path=e.path;details();return;}if(_state==DETAILS){_state=ACTIONS;setItems(_actions);return;}if(_state==ACTIONS&&i<2)Screen.push(new LfDataFormScreen(i==0?LfDataFormScreen::COPY_ITEM:LfDataFormScreen::EDIT_ITEM,_path));}
void LfDataLibraryScreen::onBack(){if(_state==ACTIONS){details();return;}if(_state==DETAILS){open();return;}Screen.goBack();}
void LfDataLibraryScreen::onUpdate(){if(_state!=DETAILS){ListScreen::onUpdate();return;}if(!Uni.Nav->wasPressed())return;auto d=Uni.Nav->readDirection();if(d==INavigation::DIR_BACK){open();return;}if(d==INavigation::DIR_PRESS){_state=ACTIONS;setItems(_actions);return;}_detailsView.onNav(d);}
void LfDataLibraryScreen::onRender(){if(_state==DETAILS){_detailsView.render(bodyX(),bodyY(),bodyW(),bodyH());return;}ListScreen::onRender();}

LfDataFormScreen::LfDataFormScreen(Mode m,const String&p):_mode(m),_path(p){}
bool LfDataFormScreen::loadBin(const String&p){auto info=LFCodec::fromFilename(p);if(!info||!Uni.Storage||!Uni.Storage->isAvailable())return false;fs::File f=Uni.Storage->open(p.c_str(),"r");if(!f||f.size()!=info->dataSize){if(f)f.close();return false;}uint8_t raw[LFCodec::kMaxDataSize]={};size_t n=f.read(raw,info->dataSize);f.close();return n==info->dataSize&&LFCodec::decode(info->protocol,raw,n,_data);}
void LfDataFormScreen::onInit(){if(_mode!=NEW_ITEM&&_path.length()){if(!loadBin(_path)){ShowStatusAction::show("Data not supported",1600);Screen.goBack();return;}_source=MANUAL;if(_mode==COPY_ITEM)_path="";}else{auto f=LFCodec::formatAt(0);if(f)LFCodec::create(f->protocol,_data);randomize();}rebuild();}
void LfDataFormScreen::randomize(){auto info=LFCodec::format(_data.protocol);if(!info||!(info->capabilities&LFCodec::CanGenerateRandom))return;LFCodec::DecodedData d;if(!LFCodec::create(_data.protocol,d))return;switch(_data.protocol){case LFCodec::Protocol::EM410X:{uint8_t raw[5];for(auto&b:raw)b=(uint8_t)esp_random();LFCodec::setField(d,LFCodec::FieldId::NumericId,LFCodec::hex(raw,5,false));break;}case LFCodec::Protocol::IoProx:LFCodec::setField(d,LFCodec::FieldId::FacilityCode,String((uint8_t)esp_random()));LFCodec::setField(d,LFCodec::FieldId::CardNumber,String((uint16_t)esp_random()));break;case LFCodec::Protocol::PACStanley:{static const char c[]="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";String id;for(uint8_t i=0;i<8;++i)id+=c[esp_random()%(sizeof(c)-1)];LFCodec::setField(d,LFCodec::FieldId::TextId,id);break;}default:return;}_data=d;}
String LfDataFormScreen::fieldValue(const LFCodec::FieldInfo&f)const{switch(f.id){case LFCodec::FieldId::NumericId:case LFCodec::FieldId::RawData:return LFCodec::hex(_data.data,_data.length,false);case LFCodec::FieldId::FacilityCode:return String(_data.facilityCode);case LFCodec::FieldId::CardNumber:return String(_data.cardNumber);case LFCodec::FieldId::TextId:return _data.hasTextId?String(_data.textId):String();}return "";}
void LfDataFormScreen::rebuild(){_preview=false;_state=FORM;uint8_t sel=_selectedIndex;_count=0;auto info=LFCodec::format(_data.protocol);auto add=[&](const char*l,const String&v){_labels[_count]=v;_items[_count]={l,_labels[_count].c_str()};++_count;};if(_mode!=NEW_ITEM){add("Type",info?info->name:"Unknown");size_t n=LFCodec::editableFieldCount(_data.protocol);for(size_t i=0;i<n&&_count<9;++i){auto f=LFCodec::editableFieldAt(_data.protocol,i);add(f->label,fieldValue(*f));}}else{if(_source!=SAVED)add("Type",info?info->name:"Select...");add("ID",_source==RANDOM?"Random":(_source==SAVED?"File":"Manual"));if(_source==SAVED){add("ID File",_savedPath.length()?stem(_savedPath):"-");if(_savedPath.length()){add("Type",info?info->name:"Unknown");LFCodec::Field f[6];size_t n=LFCodec::fields(_data,f,6);for(size_t i=0;i<n&&_count<9;++i)add(f[i].label,f[i].value);}}else if(_source==MANUAL){size_t n=LFCodec::editableFieldCount(_data.protocol);for(size_t i=0;i<n&&_count<9;++i){auto f=LFCodec::editableFieldAt(_data.protocol,i);add(f->label,fieldValue(*f));}}}_items[_count++]={"View Data",nullptr};bool rawOnly=false;size_t ec=LFCodec::editableFieldCount(_data.protocol);if(ec==1){auto f=LFCodec::editableFieldAt(_data.protocol,0);rawOnly=f&&f->id==LFCodec::FieldId::RawData;}if((_mode!=NEW_ITEM||_source==MANUAL)&&!rawOnly)_items[_count++]={"Edit Data",nullptr};_items[_count++]={"Save",nullptr};setItems(_items,_count,min<uint8_t>(sel,_count-1));}
void LfDataFormScreen::types(){_state=TYPE_SELECT;_typeCount=min<size_t>(LFCodec::formatCount(),8);for(uint8_t i=0;i<_typeCount;++i){auto f=LFCodec::formatAt(i);_types[i]={f?f->name:"Unknown"};}setItems(_types,_typeCount);}
void LfDataFormScreen::sources(){_state=SOURCE_SELECT;auto info=LFCodec::format(_data.protocol);bool can=info&&(info->capabilities&LFCodec::CanGenerateRandom);if(can)setItems(_sources,3,(uint8_t)_source);else{if(_source==RANDOM)_source=MANUAL;setItems(_sources+1,2,(uint8_t)_source-1);}}
void LfDataFormScreen::files(){if(!Uni.Storage||!Uni.Storage->isAvailable()){ShowStatusAction::show("Storage unavailable",1600);rebuild();return;}_state=FILE_SELECT;_browser.root="/unigeek/rfid/ids";setItems(_browser.items(),_browser.load(this,_pickDir,".id",nullptr,BrowseFileView::STEM));}
void LfDataFormScreen::editField(size_t i){auto f=LFCodec::editableFieldAt(_data.protocol,i);if(!f)return;auto mode=f->type==LFCodec::FieldType::Hex?InputTextAction::INPUT_HEX:InputTextAction::INPUT_TEXT;String v=InputTextAction::popup(f->label,fieldValue(*f).c_str(),mode);if(!InputTextAction::wasCancelled()&&!LFCodec::setField(_data,f->id,v))ShowStatusAction::show("Invalid value",1600);rebuild();}
void LfDataFormScreen::viewData(){_preview=true;_rc=0;auto row=[&](const String&l,const String&v){if(_rc>=10)return;_rl[_rc]=l;_rv[_rc]=v;_rows[_rc]={_rl[_rc].c_str(),_rv[_rc].c_str()};++_rc;};auto info=LFCodec::format(_data.protocol);row("Type",info?info->name:"Unknown");row("Size",String(_data.length)+" bytes");row("Data",LFCodec::hex(_data.data,_data.length,true));_view.resetScroll();_view.setRows(_rows,_rc);render();}
void LfDataFormScreen::editData(){String v=InputTextAction::popup("LF Data (hex)",LFCodec::hex(_data.data,_data.length,false).c_str(),InputTextAction::INPUT_HEX);if(InputTextAction::wasCancelled()){rebuild();return;}LFCodec::DecodedData d;String compact=v;compact.replace(" ","");compact.replace(":","");compact.replace("-","");if(compact.length()!=_data.length*2){ShowStatusAction::show("Invalid data length",1600);rebuild();return;}uint8_t raw[LFCodec::kMaxDataSize]={};for(size_t i=0;i<_data.length;++i){char b[3]={compact[i*2],compact[i*2+1],0};char*e=nullptr;raw[i]=(uint8_t)strtoul(b,&e,16);if(!e||*e){ShowStatusAction::show("Invalid hex",1600);rebuild();return;}}if(!LFCodec::decode(_data.protocol,raw,_data.length,d)){ShowStatusAction::show("Invalid LF data",1600);rebuild();return;}_data=d;_source=MANUAL;rebuild();}
String LfDataFormScreen::suggestedName()const{auto info=LFCodec::format(_data.protocol);return String(info?info->filePrefix:"LF_Data")+"_"+LFCodec::hex(_data.data,_data.length,false);}
bool LfDataFormScreen::writeBin(const String&p){uint8_t raw[LFCodec::kMaxDataSize]={};if(!LFCodec::isComplete(_data)||!LFCodec::encode(_data,raw,sizeof(raw)))return false;fs::File f=Uni.Storage->open(p.c_str(),"w");if(!f)return false;size_t n=f.write(raw,_data.length);f.close();if(n!=_data.length)return false;memcpy(_data.data,raw,_data.length);return true;}
void LfDataFormScreen::save(){if(_source==SAVED&&!_savedPath.length()){ShowStatusAction::show("Select ID file",1600);rebuild();return;}if(!Uni.Storage||!Uni.Storage->isAvailable()){ShowStatusAction::show("Storage unavailable",1600);return;}String p=_path;if(!p.length()){String n=InputTextAction::popup("Save LF Data",suggestedName().c_str());if(InputTextAction::wasCancelled()){rebuild();return;}String b=clean(n);auto info=LFCodec::format(_data.protocol);if(!info||!b.length()){ShowStatusAction::show("Invalid file name",1600);return;}String required=String(info->filePrefix)+"_";if(!b.startsWith(required))b=required+b;Uni.Storage->makeDir("/unigeek");Uni.Storage->makeDir("/unigeek/rfid");p=uniquePath("/unigeek/rfid",b);}if(p.length()&&writeBin(p)){_path=p;ShowStatusAction::show(("Saved: "+bn(p)).c_str(),1600);}else ShowStatusAction::show("Failed",1600);rebuild();}
void LfDataFormScreen::onItemSelected(uint8_t i){if(_state==TYPE_SELECT){auto f=LFCodec::formatAt(i);if(f){LFCodec::create(f->protocol,_data);if(_source==RANDOM){if(f->capabilities&LFCodec::CanGenerateRandom)randomize();else _source=MANUAL;}}_selectedIndex=0;rebuild();return;}if(_state==SOURCE_SELECT){auto info=LFCodec::format(_data.protocol);bool can=info&&(info->capabilities&LFCodec::CanGenerateRandom);_source=(Source)(can?i:i+1);if(_source==RANDOM)randomize();if(_source==SAVED)_savedPath="";_selectedIndex=1;rebuild();return;}if(_state==FILE_SELECT){if(i>=_browser.count())return;auto e=_browser.entry(i);if(e.isDir){_pickDir=e.path;files();return;}LFCodec::DecodedData d;if(IdentityFile::loadLfId(e.path,d)){_data=d;_savedPath=e.path;_selectedIndex=2;rebuild();}else ShowStatusAction::show("Invalid ID file",1600);return;}uint8_t row=0;if(_mode!=NEW_ITEM){if(i==row++)return;size_t n=LFCodec::editableFieldCount(_data.protocol);if(i>=row&&i<row+n){editField(i-row);return;}row+=n;if(i==row++){viewData();return;}bool rawOnly=false;size_t ec=LFCodec::editableFieldCount(_data.protocol);if(ec==1){auto f=LFCodec::editableFieldAt(_data.protocol,0);rawOnly=f&&f->id==LFCodec::FieldId::RawData;}if(!rawOnly&&i==row++){editData();return;}if(i==row)save();return;}if(_source!=SAVED){if(i==row++){types();return;}}if(i==row++){sources();return;}if(_source==SAVED){if(i==row++){files();return;}if(_savedPath.length()){auto info=LFCodec::format(_data.protocol);if(i==row++)return;LFCodec::Field f[6];size_t n=LFCodec::fields(_data,f,6);if(i>=row&&i<row+n)return;row+=n;}}else if(_source==MANUAL){size_t n=LFCodec::editableFieldCount(_data.protocol);if(i>=row&&i<row+n){editField(i-row);return;}row+=n;}if(i==row++){viewData();return;}bool rawOnly=false;size_t ec=LFCodec::editableFieldCount(_data.protocol);if(ec==1){auto f=LFCodec::editableFieldAt(_data.protocol,0);rawOnly=f&&f->id==LFCodec::FieldId::RawData;}if(_source==MANUAL&&!rawOnly&&i==row++){editData();return;}if(i==row)save();}
void LfDataFormScreen::onBack(){if(_state!=FORM){rebuild();return;}Screen.goBack();}
void LfDataFormScreen::onUpdate(){if(_preview){if(Uni.Nav->wasPressed()){auto d=Uni.Nav->readDirection();if(d==INavigation::DIR_BACK){rebuild();return;}_view.onNav(d);}return;}ListScreen::onUpdate();}
void LfDataFormScreen::onRender(){if(_preview){_view.render(bodyX(),bodyY(),bodyW(),bodyH());return;}ListScreen::onRender();}
