#include "NdefToolsScreen.h"
#include "core/Device.h"
#include "core/ScreenManager.h"
#include "ui/actions/InputTextAction.h"
#include "ui/actions/ShowStatusAction.h"
#include "utils/nfc/NdefBuilder.h"

namespace {
constexpr size_t MAXN=491;
String bn(const String&p){int s=p.lastIndexOf('/');return s>=0?p.substring(s+1):p;}
String stem(String p){p=bn(p);if(p.endsWith(".ndef"))p.remove(p.length()-5);return p;}
String clean(String n){n.trim();if(n.endsWith(".ndef"))n.remove(n.length()-5);for(int i=0;i<(int)n.length();++i){char c=n[i];bool ok=isAlphaNumeric(c)||c=='-'||c=='_';if(!ok)n.setCharAt(i,'_');}while(n.indexOf("__")>=0)n.replace("__","_");while(n.startsWith("_"))n.remove(0,1);while(n.endsWith("_"))n.remove(n.length()-1);return n;}
String uniquePath(const String&dir,const String&base){String p=dir+"/"+base+".ndef";if(!Uni.Storage->exists(p.c_str()))return p;for(int n=2;n<1000;++n){p=dir+"/"+base+"_("+String(n)+").ndef";if(!Uni.Storage->exists(p.c_str()))return p;}return "";}
String uriPrefix(uint8_t c){switch(c){case 0x00:return"";case 0x01:return"http://www.";case 0x02:return"https://www.";case 0x03:return"http://";case 0x04:return"https://";case 0x05:return"tel:";case 0x06:return"mailto:";case 0x07:return"ftp://anonymous:anonymous@";case 0x08:return"ftp://ftp.";case 0x09:return"ftps://";case 0x0A:return"sftp://";case 0x0B:return"smb://";case 0x0C:return"nfs://";case 0x0D:return"ftp://";case 0x0E:return"dav://";case 0x0F:return"news:";case 0x10:return"telnet://";case 0x11:return"imap:";case 0x12:return"rtsp://";case 0x13:return"urn:";case 0x14:return"pop:";case 0x15:return"sip:";case 0x16:return"sips:";case 0x17:return"tftp:";case 0x18:return"btspp://";case 0x19:return"btl2cap://";case 0x1A:return"btgoep://";case 0x1B:return"tcpobex://";case 0x1C:return"irdaobex://";case 0x1D:return"file://";case 0x1E:return"urn:epc:id:";case 0x1F:return"urn:epc:tag:";case 0x20:return"urn:epc:pat:";case 0x21:return"urn:epc:raw:";case 0x22:return"urn:epc:";case 0x23:return"urn:nfc:";default:return"";}}
String vcUnescape(const String&v){String o;for(int i=0;i<(int)v.length();++i){char c=v[i];if(c=='\\'&&i+1<(int)v.length()){char n=v[++i];if(n=='n'||n=='N')o+='\n';else o+=n;}else o+=c;}return o;}
String vc(const String&card,const char*k){int p=0;String a=String(k)+":";while(p<(int)card.length()){int e=card.indexOf('\n',p);if(e<0)e=card.length();String l=card.substring(p,e);if(l.endsWith("\r"))l.remove(l.length()-1);if(l.startsWith(a))return vcUnescape(l.substring(a.length()));String s=String(k)+";";if(l.startsWith(s)){int c=l.indexOf(':');if(c>=0)return vcUnescape(l.substring(c+1));}p=e+1;}return"";}
bool parseRecord(const uint8_t*n,size_t len,int&type,String&text,String&url,String&phone,String&email,String&name,String&company,String&address,String&vp,String&ve,String&web){type=-1;if(!n||len<3)return false;size_t p=0;uint8_t h=n[p++];if(!(h&0x80)||!(h&0x40)||(h&0x20))return false;bool sr=h&0x10,il=h&8;uint8_t tnf=h&7,tl=n[p++];uint32_t pl=0;if(sr){if(p>=len)return false;pl=n[p++];}else{if(p+4>len)return false;pl=((uint32_t)n[p]<<24)|((uint32_t)n[p+1]<<16)|((uint32_t)n[p+2]<<8)|n[p+3];p+=4;}uint8_t id=0;if(il){if(p>=len)return false;id=n[p++];}if(p+tl+id+pl!=len)return false;const uint8_t*t=n+p;p+=tl+id;const uint8_t*pay=n+p;if(tnf==1&&tl==1&&t[0]=='T'&&pl>=1){uint8_t st=pay[0],ll=st&0x3f;if(1+ll>pl)return false;if(st&0x80)return true;for(size_t i=1+ll;i<pl;++i)text+=(char)pay[i];type=0;return true;}if(tnf==1&&tl==1&&t[0]=='U'&&pl>=1){if(pay[0]>0x23)return true;String u=uriPrefix(pay[0]);for(size_t i=1;i<pl;++i)u+=(char)pay[i];if(u.startsWith("tel:")){phone=u.substring(4);type=2;}else if(u.startsWith("mailto:")){email=u.substring(7);type=3;}else{url=u;type=1;}return true;}String ts;for(uint8_t i=0;i<tl;++i)ts+=(char)t[i];ts.toLowerCase();if(tnf==2&&(ts=="text/vcard"||ts=="text/x-vcard")){String c;for(size_t i=0;i<pl;++i)c+=(char)pay[i];name=vc(c,"FN");company=vc(c,"ORG");address=vc(c,"ADR");vp=vc(c,"TEL");ve=vc(c,"EMAIL");web=vc(c,"URL");type=4;return true;}return true;}
}

NdefRecordFormScreen::NdefRecordFormScreen(Mode m,const String&p,SaveCallback cb,void*ctx):_mode(m),_path(p),_cb(cb),_ctx(ctx){}
bool NdefRecordFormScreen::isValidSingleRecord(const uint8_t*b,size_t n){int t=-1;String a,b1,c,d,e,g,h,i,j,k;return parseRecord(b,n,t,a,b1,c,d,e,g,h,i,j,k);}
void NdefRecordFormScreen::onInit(){if((_mode==EDIT_FILE||_mode==COPY_FILE)&&!load(_path)){ShowStatusAction::show("Invalid NDEF record",1600);Screen.goBack();return;}if(_mode==COPY_FILE)_path="";rebuild();}
bool NdefRecordFormScreen::load(const String&p){if(!Uni.Storage||!Uni.Storage->isAvailable())return false;fs::File f=Uni.Storage->open(p.c_str(),"r");if(!f||!f.size()||f.size()>MAXN){if(f)f.close();return false;}uint8_t b[MAXN];size_t n=f.read(b,f.size());f.close();return parse(b,n);}
bool NdefRecordFormScreen::parse(const uint8_t*b,size_t n){int t=-1;_text=_url=_phone=_email=_name=_company=_address=_vphone=_vemail=_website="";if(!parseRecord(b,n,t,_text,_url,_phone,_email,_name,_company,_address,_vphone,_vemail,_website)||t<0)return false;_type=(Type)t;return true;}
void NdefRecordFormScreen::rebuild(){_preview=false;_state=FORM;uint8_t sel=_selectedIndex;_count=0;auto add=[&](const char*l,const String&v){_vals[_count]=v.length()?v:"-";_items[_count]={l,_vals[_count].c_str()};++_count;};static const char*tn[]={"Text","URL","Phone","Email","vCard"};add("Type",tn[_type]);if(_type==TEXT)add("Text",_text);else if(_type==URL)add("URL",_url);else if(_type==PHONE)add("Phone",_phone);else if(_type==EMAIL)add("Email",_email);else{add("Name",_name);add("Company",_company);add("Address",_address);add("Phone",_vphone);add("Email",_vemail);add("Website",_website);}_items[_count++]={"Preview",nullptr};_items[_count++]={"Save",nullptr};setItems(_items,_count,min<uint8_t>(sel,_count-1));}
void NdefRecordFormScreen::selectType(){_state=TYPE_SELECT;setItems(_types,5);}
void NdefRecordFormScreen::editField(uint8_t i){String*v=nullptr;const char*title="Value";InputTextAction::Mode mode=InputTextAction::INPUT_TEXT;if(_type==TEXT){v=&_text;title="Text";}else if(_type==URL){v=&_url;title="URL";}else if(_type==PHONE){v=&_phone;title="Phone";mode=InputTextAction::INPUT_PHONE;}else if(_type==EMAIL){v=&_email;title="Email";}else{String*vs[]={&_name,&_company,&_address,&_vphone,&_vemail,&_website};const char*ts[]={"Name","Company","Address","Phone","Email","Website"};v=vs[i];title=ts[i];if(i==3)mode=InputTextAction::INPUT_PHONE;}String x=InputTextAction::popup(title,v->c_str(),mode);if(!InputTextAction::wasCancelled())*v=x;rebuild();}
bool NdefRecordFormScreen::complete()const{if(_type==TEXT)return _text.length();if(_type==URL)return _url.length();if(_type==PHONE)return _phone.length();if(_type==EMAIL)return _email.length();return _name.length();}
bool NdefRecordFormScreen::build(uint8_t*out,size_t&n){n=0;if(!complete())return false;if(_type==TEXT)return NdefBuilder::buildText(_text,out,n,MAXN);if(_type==URL)return NdefBuilder::buildUrl(_url,out,n,MAXN);if(_type==PHONE)return NdefBuilder::buildPhone(_phone,out,n,MAXN);if(_type==EMAIL)return NdefBuilder::buildEmail(_email,out,n,MAXN);return NdefBuilder::buildVcard(_name,_company,_address,_vphone,_vemail,_website,out,n,MAXN);}
void NdefRecordFormScreen::preview(){uint8_t b[MAXN];size_t n=0;if(!build(b,n)){ShowStatusAction::show(complete()?"NDEF too large":"Complete required fields",1600);rebuild();return;}_preview=true;_rc=0;auto row=[&](const String&l,const String&v){if(_rc>=32)return;_rl[_rc]=l;_rv[_rc]=v;_rows[_rc]={_rl[_rc].c_str(),_rv[_rc].c_str()};++_rc;};static const char*tn[]={"Text","URL","Phone","Email","vCard"};row("Type",tn[_type]);if(_type==TEXT)row("Text",_text);else if(_type==URL)row("URL",_url);else if(_type==PHONE)row("Phone",_phone);else if(_type==EMAIL)row("Email",_email);else{row("Name",_name);row("Company",_company);row("Address",_address);row("Phone",_vphone);row("Email",_vemail);row("Website",_website);}row("Size",String((unsigned)n)+" bytes");_view.resetScroll();_view.setRows(_rows,_rc);render();}
String NdefRecordFormScreen::suggested()const{if(_type==VCARD)return _name.length()?clean(_name):"vcard";if(_type==URL)return"url";if(_type==PHONE)return"phone";if(_type==EMAIL)return"email";return"text";}
void NdefRecordFormScreen::save(){uint8_t b[MAXN];size_t n=0;if(!build(b,n)){ShowStatusAction::show(complete()?"NDEF too large":"Complete required fields",1600);rebuild();return;}if(_mode==BUFFER){if(_cb&&_cb(_ctx,b,n)){ShowStatusAction::show("NDEF updated",1200);Screen.goBack();}else{ShowStatusAction::show("Failed",1600);rebuild();}return;}if(!Uni.Storage||!Uni.Storage->isAvailable()){ShowStatusAction::show("Storage unavailable",1600);rebuild();return;}String p=_path;if(!p.length()){String nm=InputTextAction::popup("Save NDEF",suggested().c_str());if(InputTextAction::wasCancelled()){rebuild();return;}String base=clean(nm);if(!base.length()){ShowStatusAction::show("Invalid file name",1600);rebuild();return;}Uni.Storage->makeDir("/unigeek/nfc");Uni.Storage->makeDir("/unigeek/nfc/ndefs");p=uniquePath("/unigeek/nfc/ndefs",base);}fs::File f=Uni.Storage->open(p.c_str(),"w");bool ok=f&&f.write(b,n)==n;if(f)f.close();if(ok){_path=p;ShowStatusAction::show(("Saved: "+bn(p)).c_str(),1600);}else ShowStatusAction::show("Failed",1600);rebuild();}
void NdefRecordFormScreen::onItemSelected(uint8_t i){if(_state==TYPE_SELECT){_type=(Type)i;_text=_url=_phone=_email=_name=_company=_address=_vphone=_vemail=_website="";_selectedIndex=0;rebuild();return;}uint8_t r=0;if(i==r++){if(_mode==NEW_FILE||_mode==BUFFER)selectType();return;}uint8_t fields=_type==VCARD?6:1;if(i>=r&&i<r+fields){editField(i-r);return;}r+=fields;if(i==r++){preview();return;}if(i==r)save();}
void NdefRecordFormScreen::onBack(){if(_preview){rebuild();return;}if(_state!=FORM){rebuild();return;}Screen.goBack();}
void NdefRecordFormScreen::onUpdate(){if(_preview){if(Uni.Nav->wasPressed()){auto d=Uni.Nav->readDirection();if(d==INavigation::DIR_BACK){rebuild();return;}_view.onNav(d);}return;}ListScreen::onUpdate();}
void NdefRecordFormScreen::onRender(){if(_preview){_view.render(bodyX(),bodyY(),bodyW(),bodyH());return;}ListScreen::onRender();}

const char* NdefLibraryScreen::title(){return _state==BROWSE?"Saved NDEF Records":(_state==DETAILS?"NDEF Details":"NDEF Actions");}
void NdefLibraryScreen::onInit(){browse();}
void NdefLibraryScreen::browse(){_state=BROWSE;if(!Uni.Storage||!Uni.Storage->isAvailable()){ShowStatusAction::show("Storage unavailable",1600);Screen.goBack();return;}Uni.Storage->makeDir("/unigeek/nfc");Uni.Storage->makeDir(_dir.c_str());_browser.root=_dir;setItems(_browser.items(),_browser.load(this,_pick,".ndef",nullptr,BrowseFileView::STEM));}
bool NdefLibraryScreen::inspect(const String&p){if(!Uni.Storage||!Uni.Storage->isAvailable())return false;fs::File f=Uni.Storage->open(p.c_str(),"r");if(!f||!f.size()||f.size()>MAXN){if(f)f.close();return false;}uint8_t b[MAXN];_len=f.size();size_t n=f.read(b,_len);f.close();if(n!=_len)return false;int t=-1;String a,b1,c,d,e,g,h,i,j,k;if(!parseRecord(b,n,t,a,b1,c,d,e,g,h,i,j,k))return false;_editable=t>=0;return true;}
void NdefLibraryScreen::details(){_state=DETAILS;_dc=0;auto add=[&](String l,String v){_dl[_dc]=l;_dv[_dc]=v;_details[_dc]={_dl[_dc].c_str(),_dv[_dc]};++_dc;};add("File",bn(_path));add("Editable",_editable?"Yes":"No");add("Size",String((unsigned)_len)+" bytes");_details[_dc++]={"[Press]","Actions"};_detailsView.resetScroll();_detailsView.setRows(_details,_dc);}
void NdefLibraryScreen::copyRaw(){if(!Uni.Storage||!Uni.Storage->isAvailable()){ShowStatusAction::show("Storage unavailable",1600);details();return;}fs::File f=Uni.Storage->open(_path.c_str(),"r");if(!f){ShowStatusAction::show("Failed",1600);details();return;}const size_t sz=f.size();if(!sz||sz>MAXN){f.close();ShowStatusAction::show("Invalid NDEF record",1600);details();return;}uint8_t b[MAXN];size_t n=f.read(b,sz);f.close();if(n!=sz){ShowStatusAction::show("Failed",1600);details();return;}String nm=InputTextAction::popup("Save NDEF",(stem(_path)+"_copy").c_str());if(InputTextAction::wasCancelled()){details();return;}String base=clean(nm);if(!base.length()){ShowStatusAction::show("Invalid file name",1600);details();return;}String p=uniquePath(_dir,base);fs::File o=Uni.Storage->open(p.c_str(),"w");bool ok=o&&o.write(b,n)==n;if(o)o.close();if(ok)ShowStatusAction::show(("Saved: "+bn(p)).c_str(),1600);else ShowStatusAction::show("Failed",1600);details();}
void NdefLibraryScreen::onItemSelected(uint8_t i){if(_state==BROWSE){if(i>=_browser.count())return;auto e=_browser.entry(i);if(e.isDir){_pick=e.path;browse();return;}_path=e.path;if(!inspect(_path)){ShowStatusAction::show("Invalid NDEF record",1600);return;}details();return;}if(_state==DETAILS){_state=ACTIONS;_ac=0;_actions[_ac++]={"Create Copy"};if(_editable)_actions[_ac++]={"Edit"};setItems(_actions,_ac);return;}if(i==0){if(_editable)Screen.push(new NdefRecordFormScreen(NdefRecordFormScreen::COPY_FILE,_path));else copyRaw();return;}if(i==1&&_editable)Screen.push(new NdefRecordFormScreen(NdefRecordFormScreen::EDIT_FILE,_path));}
void NdefLibraryScreen::onBack(){if(_state==ACTIONS){details();return;}if(_state==DETAILS){browse();return;}Screen.goBack();}
void NdefLibraryScreen::onUpdate(){if(_state!=DETAILS){ListScreen::onUpdate();return;}if(!Uni.Nav->wasPressed())return;auto d=Uni.Nav->readDirection();if(d==INavigation::DIR_BACK){browse();return;}if(d==INavigation::DIR_PRESS){_state=ACTIONS;_ac=0;_actions[_ac++]={"Create Copy"};if(_editable)_actions[_ac++]={"Edit"};setItems(_actions,_ac);return;}_detailsView.onNav(d);}
void NdefLibraryScreen::onRender(){if(_state==DETAILS){_detailsView.render(bodyX(),bodyY(),bodyW(),bodyH());return;}ListScreen::onRender();}
